### ISSUE TITLE
Unable to get pip install to work: Window 10, Anaconda 2.

### ISSUE THREAD

**Issue by richkatz** [darvid/python-hyperscan#2]
pip install hyperscan
Collecting hyperscan
  Using cached hyperscan-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\richkatz\appdata\local\temp\pip-build-a7rgfv\hyperscan\setup.py", line 74, in <module>
        setup()
      File "c:\users\richkatz\appdata\local\temp\pip-build-a7rgfv\hyperscan\setup.py", line 32, in setup
        'pkg-config', '--cflags', 'libhs']).decode('utf-8'),
      File "c:\users\richkatz\anaconda2\lib\subprocess.py", line 567, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "c:\users\richkatz\anaconda2\lib\subprocess.py", line 711, in __init__
        errread, errwrite)
      File "c:\users\richkatz\anaconda2\lib\subprocess.py", line 959, in _execute_child
        startupinfo)
    WindowsError: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\richkatz\appdata\local\temp\pip-build-a7rgfv\hyperscan\

**Comment by darvid** [comment]
Please note that building on Windows is largely unsupported. I'm not even sure that the Hyperscan project itself has instructions on building for Windows. It might be possible, however, I just have never tested it. This particular error is complaining about pkg-config, so you may have luck installing [MinGW](http://www.mingw.org/wiki/FAQ), installing all the dependencies, and then building. But it will be quite the struggle.

Since you're on Windows 10, though, it might just be easier to use [WSL](https://msdn.microsoft.com/en-us/commandline/wsl/about) and follow the Linux build instructions.

**Comment by richkatz** [comment]
Hi Darvid,

Thanks.  I have some Ubuntu VMs.  On Ubuntu I get a more specific error that libhs isn't found.

$ pip install hyperscan
Collecting hyperscan
  Downloading hyperscan-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Package libhs was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libhs.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libhs' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yrvK5I/hyperscan/setup.py", line 74, in <module>
        setup()
      File "/tmp/pip-build-yrvK5I/hyperscan/setup.py", line 32, in setup
        'pkg-config', '--cflags', 'libhs']).decode('utf-8'),
      File "/home/richkatz/anaconda2/lib/python2.7/subprocess.py", line 219, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['pkg-config', '--cflags', 'libhs']' returned non-zero exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yrvK5I/hyperscan/


 Thank you for your help.

Best,

Richard

**Comment by darvid** [comment]
Sorry the install docs are lacking a bit. You need to build and install Hyperscan first. 

The Hyperscan docs seem to have moved but I can't find a current URL, for now you can use the guide from the official repository [here](https://github.com/intel/hyperscan/blob/master/doc/dev-reference/getting_started.rst). Note the dependencies, you will need to install CMake, Ragel, Python headers, and Boost. I'll try to write a detailed installation guide as soon as I get the chance this week, but in the interim let's see how far the guide can get you. 

I remember having to build Boost from source because a recent package wasn't available on Ubuntu. Try following [this guide](https://shortrecipes.blogspot.com/2015/02/ubuntu-1404-install-boost-157.html) to build and install Boost 1.57 on Ubuntu. 

Once you have all the dependencies, you can install Hyperscan as follows in [this guide](https://github.com/darvid/python-hyperscan/blob/master/docs/source/index.rst#building-hyperscan).

Sorry this is all over the place. Let me know how it goes.

**Comment by richkatz** [comment]
HI Darvid,

I was able to find this page which either you or someone named Travis wrote and it had decent instructions:

https://github.com/darvid/python-hyperscan/blob/master/.travis.yml

I was able to get the build to work.  Following the instructions with only minimal modifications. However cmake left me with an error: " Ragel state machine compiler not found"


903  sudo ./b2 install

  909  git clone https://github.com/01org/hyperscan.git
  910  cd hyperscan
  911  mkdir -p build
  912  cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON ../

And then I get this error where CMakeLists.txt was missing from the boost directory. So I did

cp CMakeLists.txt  ..

Now I have this error:

Ragel state machine compiler not found

I was first guessing this might be a directory positioning  issue of some sort because I had to cp the CMakeLists.txt file to the directory above.  




richkatz@richkatz-VirtualBox:~/ws/boost/boost_1_57_0/hyperscan$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON ../
CMake Error at CMakeLists.txt:20 (include):
  include could not find load file:

    /home/richkatz/ws/boost/boost_1_57_0/cmake/platform.cmake


CMake Error at CMakeLists.txt:21 (include):
  include could not find load file:

    /home/richkatz/ws/boost/boost_1_57_0/cmake/ragel.cmake


-- Build type RELWITHDEBINFO
CMake Error at CMakeLists.txt:71 (include):
  include could not find load file:

    /home/richkatz/ws/boost/boost_1_57_0/cmake/boost.cmake


-- Build date: 2017-11-15
CMake Error at CMakeLists.txt:96 (message):
  Ragel state machine compiler not found


-- Configuring incomplete, errors occurred!

Thank you for your help.

All the best,

Richard

**Comment by darvid** [comment]
Completely forgot about that, [Travis](https://travis-ci.org/) is actually a continuous integration (CI) service, and that file essentially builds both Hyperscan and the Python extension on an Ubuntu virtual machine, so you are correct, those steps should be able to be replicated to build on your own VM. 

It looks like I have a bug in that Travis configuration file - there should be a ``cd build`` step in between the ``mkdir -p build`` and the ``cmake`` command. You shouldn't have to copy CMakeLists anywhere, you can safely delete it from the parent directory (I'm assuming the boost directory). Just ``cd`` to the ``hyperscan/build`` directory and then run cmake from there, and that should work.
