### ISSUE TITLE
Can't import from hyperscan in python 3.12

### ISSUE THREAD

**Issue by ekneg54** [darvid/python-hyperscan#98]
I was able to install via pip, but if I try to import hyperscan, python complains about it can't find the module `hyperscan._hyperscan` as seen here:

<img width="885" alt="image" src="https://github.com/darvid/python-hyperscan/assets/101292599/6cf4c464-8794-44fe-acc0-b6c3851a11ae">

**Comment by betterlch** [comment]
Have a try: https://github.com/darvid/python-hyperscan/issues/30#issuecomment-1605627150

**Comment by ekneg54** [comment]
yes... this does the job. but could we get an installable package? 
we redistribute hyperscan in our product and it is a poor solution to manually do this renaming after install :-/

**Comment by ekneg54** [comment]
by running our tests we saw, that the import error disappeared but die lib is not working anymore. It does nothing.

**Comment by darvid** [comment]
please try one of the 3.12 wheels from here: https://github.com/darvid/python-hyperscan/actions/runs/6918986174 

I will try to get CI updated soon to force push them to the current release in PyPI, currently no other changes have been made to warrant a new library version, otherwise normally the wheels would be uploaded with a new release.

**Comment by ekneg54** [comment]
thank you... We will wait for the force push

**Comment by darvid** [comment]
wheels pushed

**Comment by ekneg54** [comment]
thank you very much... seems to work
